In [2]:
import numpy as np
import pandas as pd
import scipy
from sklearn import neighbors
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder

In [7]:
df = pd.read_excel('iris.xls')

In [8]:
df.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  4.7  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [9]:
df.shape

(150, 5)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [11]:
df.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [12]:
df['Classification'].value_counts(normalize = True)

Iris-versicolor    0.333333
Iris-setosa        0.333333
Iris-virginica     0.333333
Name: Classification, dtype: float64

In [10]:
#Perform Label Encoding

In [13]:
encode = LabelEncoder()
df['Classification'] = encode.fit_transform(df['Classification'])

In [12]:
#Splitting the data to Features and Labels

In [14]:
X = df[['SL','SW','PL','PW']].values
y = df['Classification'].values

In [ ]:
# Splitting data

In [15]:

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 30, test_size = 0.2)
print(X_train[0:5],'\n',y_train[0:5])

[[6.9 3.1 5.4 2.1]
 [5.5 2.4 3.7 1. ]
 [6.8 3.  5.5 2.1]
 [6.1 3.  4.9 1.8]
 [7.7 2.6 6.9 2.3]] 
 [2 1 2 2 2]


In [ ]:
#Model Training - Support Vector Machine Classification Model.

In [17]:

from sklearn.svm import SVC

In [ ]:
#RBF Kernal SVM

In [20]:

svc_model = SVC(kernel = 'rbf', degree = 3)
svc_model.fit(X_train,y_train)
svc_predt = svc_model.predict(X_test)

In [21]:
print(metrics.classification_report(y_test, svc_predt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

